version: '3.4'

services:
  client:
    image: client
    build:
      context: Application/client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5555:5555
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
