services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: gazetalk-db
    environment:
      MYSQL_ROOT_PASSWORD: Aqwer.2002
      MYSQL_DATABASE: GazeTalk
      MYSQL_ROOT_HOST: '%'
      TZ: "Asia/Bangkok"
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    build:
      context: ./backend
    container_name: gazetalk-backend
    ports:
      - "85:85"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DB_NAME: GazeTalk
      DB_USER: root
      DB_PASSWORD: Aqwer.2002
      DB_HOST: db
      DB_PORT: 3306
      PORT: 85
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./Application/client
    container_name: gazetalk-frontend
    ports:
      - "80:80"
    volumes:
      - ./Application/client:/app
      - /app/node_modules
    env_file:
    - ./Application/client/.env 
    environment:
      NODE_ENV: development

  model_text:
    build:
      context: ./model_text
    ports:
      - "83:83"
    volumes:
      - ./model_text:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  gaze_tracking:
    build:
      context: ./GazeTracking
    container_name: gazetalk-gaze-tracking
    ports:
      - "82:82"
    volumes:
      - ./GazeTracking:/app
    environment:
      - FLASK_ENV=development
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  mysql_data:
