server {
    listen 80;
    server_name 202.44.40.178;

    # เปลี่ยนเส้นทาง HTTP ไปยัง HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name 202.44.40.178;

    # กำหนด SSL certificate
    ssl_certificate /etc/ssl/certs/mydomain.crt;
    ssl_certificate_key /etc/ssl/private/mydomain.key;

    location / {
        # ส่งคำขอไปที่ frontend
        proxy_pass http://frontend:80;  # ใช้บริการ frontend ใน Docker
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        # ส่งคำขอไปที่ backend
        proxy_pass http://backend:85;  # ใช้บริการ backend ใน Docker
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
